### ISSUE TITLE
Error: spawn ENOENT on Mac OS

### ISSUE THREAD

**Issue by AlexMoroz** [gfloyd/node-unoconv#2]
I run this:

``` JavaScript
var unoconv = require('unoconv');
unoconv.convert('document.docx', 'pdf', function (err, result) {
});
```

And I have such error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

I have no idea what to do =(

**Comment by m4a1fox** [comment]
This error too.

**Comment by AlexMoroz** [comment]
I solved this problem by running unoconv via command line functions in nodejs. Maybe it will help you.

**Comment by dg92** [comment]
@AlexMoroz  how did you run unoconv?

**Comment by AlexMoroz** [comment]
@dg92 it was 3 years ago, sorry, cannot help you :)

**Comment by dg92** [comment]
@AlexMoroz Ok Thanks.

**Comment by peirceb** [comment]
I'm here because I didn't install unoconv. Make sure you install unoconv.
